import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { school } from "@/lib/site";
import { accreditationDocs, getAccreditationDoc } from "@/lib/content/accreditation";

/**
 * A single accreditation document.
 *
 * NEXT 16 NOTES:
 *  - `params` is a Promise and must be awaited. Synchronous access was removed
 *    in 16, not merely deprecated.
 *  - `PageProps<'/accreditation/[doc]'>` is a GLOBAL type helper — no import.
 *    It is generated by `next dev` / `next build` / `next typegen`, so if your
 *    editor flags it as missing, run `npx next typegen` once.
 *  - generateStaticParams prerenders all ten documents at build time, so a
 *    reviewer never waits on a server render.
 */
export function generateStaticParams() {
  return accreditationDocs.map((doc) => ({ doc: doc.slug }));
}

export async function generateMetadata({
  params,
}: PageProps<"/accreditation/[doc]">): Promise<Metadata> {
  const { doc: slug } = await params;
  const entry = getAccreditationDoc(slug);
  if (!entry) return { title: "Document not found" };

  const label = entry.meta.n === null ? "Bonus document" : `Document ${entry.meta.n} of 9`;
  return {
    title: entry.meta.title,
    description: `${label} — ${entry.meta.title}. Part of the Iowa Department of Education nonpublic school accreditation submission for ${school.legalName}.`,
  };
}

export default async function AccreditationDocPage({
  params,
}: PageProps<"/accreditation/[doc]">) {
  const { doc: slug } = await params;
  const entry = getAccreditationDoc(slug);
  if (!entry) notFound();

  const { meta, Body } = entry;
  const index = accreditationDocs.findIndex((d) => d.slug === meta.slug);
  const previous = index > 0 ? accreditationDocs[index - 1] : null;
  const next =
    index < accreditationDocs.length - 1 ? accreditationDocs[index + 1] : null;

  return (
    <article>
      <p className="text-xs font-bold uppercase tracking-[0.15em] text-gold-600">
        {meta.n === null
          ? "Bonus document"
          : `Document ${meta.n} of 9`}
      </p>

      <div className="mt-2">
        <Body />
      </div>

      {/* Packet navigation — screen only; meaningless on paper. */}
      <nav
        aria-label="Document navigation"
        className="no-print mt-14 flex flex-col gap-3 border-t border-line pt-6 sm:flex-row sm:justify-between"
      >
        {previous ? (
          <Link
            href={`/accreditation/${previous.slug}`}
            className="text-sm text-navy-700 hover:text-navy-900"
          >
            <span className="block text-xs uppercase tracking-wider text-ink-subtle">
              Previous
            </span>
            &larr; {previous.title}
          </Link>
        ) : (
          <span />
        )}

        {next ? (
          <Link
            href={`/accreditation/${next.slug}`}
            className="text-sm text-navy-700 hover:text-navy-900 sm:text-right"
          >
            <span className="block text-xs uppercase tracking-wider text-ink-subtle">
              Next
            </span>
            {next.title} &rarr;
          </Link>
        ) : (
          <span />
        )}
      </nav>
    </article>
  );
}
